services:
  reverse_proxy:
    image: nginx:stable
    container_name: reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./static_dicomweb:/var/www/html/dicomweb:ro

  ohif_viewer:
    image: ohif/app:v3.11.0
    container_name: ohiv_viewer
    volumes:
      - ./config/default.js:/usr/share/nginx/html/app-config.js:ro
