name: Publish to PyPI

# Automatically run when a tag is pushed
on:
  push:
    tags:
      - 'v*.*.*'  # Match tags like v1.0.0, v0.1.0
  workflow_dispatch:

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine
      
      - name: Build package
        run: python -m build
      
      - name: Check distribution
        run: twine check dist/*
      
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish-to-pypi:
    name: Publish to PyPI
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/static-dicomweb-creator
    permissions:
      id-token: write  # For OIDC (when using Trusted Publishing)
    
    steps:
      - name: Download distributions
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        # No 'with' clause needed when using Trusted Publishing (OIDC)
        # Uncomment the following lines to use API token instead
        # with:
        #   password: ${{ secrets.PYPI_API_TOKEN }}
